version: 2

references:

  xcode_version: &xcode_version  "9.2.0"

  container_config: &container_config
    macos:
      xcode: *xcode_version
  
  build_app: &build_app
    run:
      name: Build app
      command: source ci/scripts/build.sh

  bundler_config: &bundler_config
    run:
      name: Configure bundler
      command: source ./ci/scripts/bundler_config.sh

  install_ruby: &install_ruby
    run:
      name: Configure Ruby dependencies
      command: source ./ci/scripts/install_ruby.sh

  set_locate: &set_locate
    run:
      name: Configure utf-8 locate
      command: source ./ci/scripts/set_locate.sh

  fastlane_config: &fastlane_config
    run:
      name: Configure Fastlane environment variables
      command: source ./ci/scripts/fastlane_config.sh
  
  test_app: &test_app
    run:
      name: Test project
      command: source ./ci/scripts/test.sh
  
  install: &install
    run:
      name: Install dependencies
      command: source ./ci/scripts/install.sh
  
  keychain_add: &keychain_add
    run:
      name: Create keychain & Add certificates
      command: source ./ci/scripts/keychain_add.sh
      environment:
        CERTIFICATES_PATH: ./ci/cert
        KEYCHAIN_NAME: ios-app.keychain

  git_config: &git_config
    run:
      name: Configure github
      command: source ./ci/scripts/git_config.sh
  
  transifex: &transifex
    run:
      name: Configure Transifex
      command: source ./ci/scripts/transifex.sh
  
  deploy_develop: &deploy_develop
    run:
      name: Generate changelog, docs, coverage and snapshots
      command: source ./ci/scripts/deploy_develop.sh
      environment:
        SCRIPT_PATH: ./ci/scripts
  
  deploy_master: &deploy_master
    run:
      name: Master deploy
      command: source ./ci/scripts/deploy_master.sh
      environment:
        SCRIPT_PATH: ./ci/scripts
  
  keychain_remove: &keychain_remove
    run:
      name: Remove keychain & certificates
      command: source ./ci/scripts/keychain_remove.sh
      environment:
        KEYCHAIN_NAME: ios-app.keychain
  
  store_ipa: &store_ipa
    store_artifacts:
      path: ./$APPNAME.ipa

  create_documentation: &create_documentation
    run:
      name: Generate documentation
      command: source ci/scripts/documentation.sh
      environment:
        DOCUMENTATION_DESTINATION: development/code-documentation/
  
  create_coverage: &create_coverage
    run:
      name: Generate coverage
      command: source ci/scripts/coverage.sh
      environment:
        COVERAGE_DESTINATION: development/coverage/
        TEST_REPORT_DESTINATION: development/test-reports/

jobs:

  build:
    <<: *container_config
    steps:
      - checkout
      - *build_app

  test:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install_ruby
      - *set_locate
      - *fastlane_config
      - *test_app
  
  documentation:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *set_locate
      - *git_config
      - *create_documentation

  coverage:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *set_locate
      - *fastlane_config
      - *git_config
      - *test_app
      - *create_coverage

  deploy_develop:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *set_locate
      - *fastlane_config
      - *keychain_add
      - *git_config
      - *transifex
      - *test_app
      - *deploy_develop
      - *keychain_remove
  
  deploy_master:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install
      - *set_locate
      - *fastlane_config
      - *keychain_add
      - *git_config
      - *transifex
      - *test_app
      - *deploy_master
      - *store_ipa
      - *keychain_remove

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - documentation:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - coverage:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
