version: 2

references:

  xcode_version: &xcode_version  "9.2.0"

  container_config: &container_config
    macos:
      xcode: *xcode_version
  
  build_app: &build_app
    run:
      name: Build app
      command: source ci/scripts/build.sh

  bundler_config: &bundler_config
    run:
      name: Configure bundler
      command: source ./ci/scripts/bundler_config.sh

  install_ruby: &install_ruby
    run:
      name: Configure Ruby dependencies
      command: source ./ci/scripts/install_ruby.sh

  set_locate: &set_locate
    run:
      name: Configure utf-8 locate
      command: source ./ci/scripts/set_locate.sh

  fastlane_config: &fastlane_config
    run:
      name: Configure Fastlane environment variables
      command: source ./ci/scripts/fastlane_config.sh
  
  test_app: &test_app
    run:
      name: Test project
      command: source ./ci/scripts/test.sh
  
  install: &install
    - run:
      name: Install dependencies
      command: source ./ci/scripts/install.sh

jobs:

  build:
    <<: *container_config
    steps:
      - checkout
      - *build_app

  test:
    <<: *container_config
    steps:
      - checkout
      - *bundler_config
      - *install_ruby
      - *set_locate
      - *fastlane_config
      - *test_app

  deploy_develop:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Configure bundler
          command: source ./ci/scripts/bundler_config.sh
      - run:
          name: Install dependencies
          command: source ./ci/scripts/install.sh
      - run:
          name: Configure utf-8 locate
          command: source ./ci/scripts/set_locate.sh
      - run:
          name: Configure Fastlane environment variables
          command: source ./ci/scripts/fastlane_config.sh
      - run:
          name: Create keychain & Add certificates
          command: source ./ci/scripts/keychain_add.sh
          environment:
            CERTIFICATES_PATH: ./ci/cert
            KEYCHAIN_NAME: ios-app.keychain
      - run:
          name: Configure github
          command: source ./ci/scripts/git_config.sh
      - run:
          name: Configure Transifex
          command: source ./ci/scripts/transifex.sh
      - run:
          name: Build and Test project
          command: source ./ci/scripts/test.sh 
      - run:
          name: Generate changelog, docs, coverage and snapshots
          command: source ./ci/scripts/deploy_develop.sh
          environment:
            SCRIPT_PATH: ./ci/scripts
      - run:
          name: Remove keychain & certificates
          command: source ./ci/scripts/keychain_remove.sh
          environment:
            KEYCHAIN_NAME: ios-app.keychain
  
  deploy_master:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: Configure bundler
          command: source ./ci/scripts/bundler_config.sh
      - run:
          name: Install dependencies
          command: source ./ci/scripts/install.sh
      - run:
          name: Configure utf-8 locate
          command: source ./ci/scripts/set_locate.sh
      - run:
          name: Configure Fastlane environment variables
          command: source ./ci/scripts/fastlane_config.sh
      - run:
          name: Create keychain & Add certificates
          command: source ./ci/scripts/keychain_add.sh
          environment:
            CERTIFICATES_PATH: ./ci/cert
            KEYCHAIN_NAME: ios-app.keychain
      - run:
          name: Configure github
          command: source ./ci/scripts/git_config.sh
      - run:
          name: Configure Transifex
          command: source ./ci/scripts/transifex.sh
      - run:
          name: Master deploy
          command: source ./ci/scripts/deploy_master.sh
          environment:
            SCRIPT_PATH: ./ci/scripts
      - store_artifacts:
          path: ./$APPNAME.ipa
      - run:
          name: Remove keychain & certificates
          command: source ./ci/scripts/keychain_remove.sh
          environment:
            KEYCHAIN_NAME: ios-app.keychain

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          filters:
            branches:
              ignore: 
                - develop
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: 
                - develop
      - deploy_master:
          requires:
            - test
          filters:
            branches:
              only: 
                - master
